on:
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore EntityFrameworkCore.Utils.slnf

      - name: Build
        run: dotnet build EntityFrameworkCore.Utils.slnf --configuration Release --no-restore

      - name: Pack
        run: dotnet pack EntityFrameworkCore.Utils.slnf --configuration Release --no-build --output ./nupkgs -p:PackageVersion=${{ github.ref_name }}

      - name: Publish to Nuget Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          OWNER: feedboards

      - name: Cleanup
        run: rm -rf ./nupkgs
